# Generated by Django 6.0 on 2025-12-19 08:41

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_room_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('country', models.CharField(db_index=True, max_length=255)),
                ('phone', models.CharField(max_length=100)),
                ('star_rating', models.IntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='room',
            name='cat',
        ),
        migrations.RemoveField(
            model_name='room',
            name='user',
        ),
        migrations.CreateModel(
            name='Room_types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField(max_length=255)),
                ('base_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('max_guests', models.IntegerField(db_index=True, max_length=2)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.hotels')),
            ],
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
