# Generated by Django 6.0 on 2025-12-19 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_hotels_remove_room_cat_remove_room_user_room_types_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(db_index=True)),
                ('floor', models.IntegerField(max_length=100)),
                ('is_available', models.BooleanField(default=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.hotels')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.room_types')),
            ],
        ),
    ]
