# Generated by Django 6.0 on 2025-12-19 11:15

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0005_rooms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_index=True, max_length=100)),
                ('last_name', models.CharField(db_index=True, max_length=150)),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='phone')),
                ('passport', models.CharField(max_length=100)),
                ('registration_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
