# Generated by Django 6.0 on 2025-12-19 11:39

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0006_guests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='phone'),
        ),
    ]
