# Generated by Django 6.0 on 2025-12-19 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0007_alter_hotels_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room_types',
            name='max_guests',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='floor',
            field=models.IntegerField(),
        ),
    ]
