# Generated by Django 6.0 on 2025-12-20 09:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0008_alter_room_types_max_guests_alter_rooms_floor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='star_rating',
            field=models.IntegerField(db_index=True, validators=[django.core.validators.MaxValueValidator(7), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField()),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.guests')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.rooms')),
            ],
        ),
    ]
