# Generated by Django 6.0 on 2025-12-22 08:38

import datetime
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0009_alter_hotels_star_rating_bookings'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='check_out_date',
            field=models.DateField(default=datetime.datetime(2025, 12, 22, 8, 36, 55, 885911, tzinfo=datetime.timezone.utc), verbose_name='departure'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookings',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='bookings',
            name='status',
            field=models.CharField(db_index=True, default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookings',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='check_in_date',
            field=models.DateField(verbose_name='arrival'),
        ),
    ]
